### ISSUE TITLE
Does it really works, do you use it?

### ISSUE THREAD

**Issue by makarid** [fercp/starkex#2]
Hello, first of all thanks for the release that you created,i am using Jitpack so i will create a clone of this repo and download it to the library via this service. Also i needed to downgrade it to Java 8 in order to add it to the library. Anyway i will add your library to Xchange library. If you have time, can you please tell me if you are using it with success, because i am trying to sign an order and i am getting "Invalid signature for order" error from the dydx endpoint. Is it maybe because we need to add more params on the StarkwareOrder? Thanks

**Comment by fercp** [comment]
hello, 
yes it was working.there are some companies using this library.
can you share me your test code so I can review it ?

**Comment by makarid** [comment]
Hello and thank you for your fast response. My test is this: 

https://github.com/makarid/starkex/blob/main/src/test/java/com/fersoft/signature/DydxPlaceOrderTest.java

Just create a keys.properties file on the test resources and add the values that needed.

**Comment by makarid** [comment]
This is the error that i am getting: {"errors":[{"msg":"Invalid signature for order"}]}

**Comment by makarid** [comment]
Is it maybe the format of the timestamp? Because the other thing that crossed my mind is that we need to include postOnly or other infos to the order signature.

**Comment by makarid** [comment]
I found the issue, you have add the ROPSTEN testnet but the Dydx have a testnet on Goerlic, so i just need to change the collateralAddressId to Goerlic and the id to 5. Thank you very much for your help!
